namespace fix
robotont/robotont_gazebo pull request #22
Opened 2020-11-16 23:08 UTC by Veix123

hotfix for #20

2020-11-17 11:23 UTC, kruusamae requested changes

2020-11-17 11:23 UTC, kruusamae commented on launch/gazebo.launch
> +    <node ns="robotont" name="spawn_urdf" pkg="gazebo_ros" type="spawn_model" args="-param /robotont/robot_description -urdf -x -$(arg x_pos) -model robotont" />
ega siin ei toimu nüüd topelt namespace'imist? ma enam ei suuda ei roboti mudelit ega laserscani rvizis visualiseerida

2020-11-17 11:23 UTC, kruusamae commented on launch/gazebo.launch
> +    <node ns="robotont" name="spawn_urdf" pkg="gazebo_ros" type="spawn_model" args="-param /robotont/robot_description -urdf -x -$(arg x_pos) -model robotont" />
pidin rvizi robot_descriptioni muutma robotont/robot_description'iks, siis kadusid TF errorid

2020-11-17 11:23 UTC, kruusamae commented on launch/gazebo.launch
> +    <node ns="robotont" name="spawn_urdf" pkg="gazebo_ros" type="spawn_model" args="-param /robotont/robot_description -urdf -x -$(arg x_pos) -model robotont" />
ja scani ei õnnestu mul üldse visualiseerida. LaserScan plugin annab errorit: `For frame [robotont/hokuyo_link]: Frame [robotont/hokuyo_link] does not exist`

2020-11-17 16:17 UTC, kruusamae commented on launch/gazebo.launch
> +    <node ns="robotont" name="spawn_urdf" pkg="gazebo_ros" type="spawn_model" args="-param /robotont/robot_description -urdf -x -$(arg x_pos) -model robotont" />
oh pagan. siin on probleem pisut laiem. meil ei ole ühtne descriptioni parameetriserverisse laadimine. mõni launch laadib robotont/robot_description, teine jälle otse robot_descriptionisse.

ilmselt on lahendus luua description kimpudesse oma upload-launchid, mis tegelevad parameetriserverisse kirjelduse laadimisega ning ükski teine kimp ei tee omaloomingut, vaid kasutab neid uploadereid.

teen selle kohta eraldi issue

2020-11-30 08:27 UTC, kruusamae commented
@Veix123 mis me selle PRiga teeme. siin on nüüd see dependency lisatud. hästi nagu ei sobi selle PRi sisse. eriti kuna see ns'i asi tuleks nüüd igalt poolt ära koristada ja samas peaks alati uue launch-faili testimine käima lisaks ka __ns abil, et näha kas sama asi toimib nii ilma kui koos ns'iga

2020-12-01 00:04 UTC, Veix123 commented
Teeme eraldi harud ja paneme selle siin kinni?

2020-12-01 08:29 UTC, closed without merging